export const player = {
    name: "testPlayer",
    maxHP: 50000,
    attack: 1000,
    deck: [{
        name: "cp加速",
        count: 8
    }, {
        name: "攻撃力強化Lv2",
        count: 4
    }, {
        name: "攻撃力強化Lv4",
        count: 4
    }, {
        name: "火傷付与Lv2",
        count: 3
    }, {
        name: "火傷付与Lv3",
        count: 3
    }, {
        name: "攻撃",
        count: 5
    }, {
        name: "無効化",
        count: 2
    }, {
        name: "回復Lv2",
        count: 3
    }, {
        name: "毒付与Lv4",
        count: 3
    }, {
        name: "模倣",
        count: 2
    }, {
        name: "連続攻撃",
        count: 5
    }, {
        name: "攻撃力強化+吸血付与",
        count: 3
    }, {
        name: "リセット",
        count: 2
    }, {
        name: "強攻撃",
        count: 3
    }, {
        name: "毒攻撃",
        count: 3
    }]
}

export const sandBag = {
    name: "sandBag",
    maxHP: 10000,
    attack: 1000,
    deck: [{
        name: "cp加速",
        count: 8
    }, {
        name: "攻撃力強化Lv2",
        count: 4
    }, {
        name: "攻撃力強化Lv4",
        count: 4
    }, {
        name: "火傷付与Lv2",
        count: 3
    }, {
        name: "火傷付与Lv3",
        count: 3
    }, {
        name: "攻撃",
        count: 5
    }, {
        name: "無効化",
        count: 2
    }, {
        name: "回復Lv2",
        count: 3
    }, {
        name: "毒付与Lv4",
        count: 3
    }, {
        name: "模倣",
        count: 2
    }, {
        name: "連続攻撃",
        count: 5
    }, {
        name: "攻撃力強化+吸血付与",
        count: 3
    }, {
        name: "リセット",
        count: 2
    }, {
        name: "強攻撃",
        count: 3
    }, {
        name: "毒攻撃",
        count: 3
    }]
}